spring:
    datasource:
        url: jdbc:mysql://192.168.40.238:3306/movie_qa?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 12345678
    redis:
        host: 192.168.40.5